src/etools_datamart/api/urls.py
from django.urls import include, path, re_path

from unicef_rest_framework.routers import APIReadOnlyRouter

from etools_datamart.api.endpoints import schema_view

# urlpatterns = router.urls
from . import endpoints

app_name = "api"


class ReadOnlyRouter(APIReadOnlyRouter):
    pass


router = ReadOnlyRouter()
router.register(r"datamart/workspaces", endpoints.WorkspaceViewSet)

router.register(r"datamart/attachment/attachment", endpoints.AttachmentViewSet)
router.register(r"datamart/funds/grants", endpoints.GrantViewSet)
router.register(r"datamart/funds/fundsreservationheader", endpoints.FundsReservationHeaderViewSet)
router.register(r"datamart/audit/audit", endpoints.AuditViewSet)
router.register(r"datamart/audit/engagements", endpoints.EngagementViewSet)
router.register(r"datamart/audit/engagement-details", endpoints.EngagementDetailViewSet, basename="engagement-details")
router.register(r"datamart/audit/financial-findings", endpoints.AuditFinancialFindingViewSet)
router.register(r"datamart/audit/micro-assessment", endpoints.MicroAssessmentViewSet)
router.register(r"datamart/audit/results", endpoints.AuditResultViewSet)
router.register(r"datamart/audit/special-audit", endpoints.AuditSpecialViewSet)
router.register(r"datamart/audit/spot-check-findings", endpoints.SpotCheckFindingViewSet)
router.register(r"datamart/actionpoints", endpoints.ActionPointViewSet)
router.register(r"datamart/locations", endpoints.LocationViewSet)
router.register(r"datamart/location-sites", endpoints.LocationSiteViewSet)
router.register(r"datamart/office", endpoints.OfficeViewSet)
router.register(r"datamart/fam-indicators", endpoints.FAMIndicatorViewSet)
router.register(r"datamart/fm-questions", endpoints.FMQuestionViewSet)
router.register(r"datamart/fm-ontrack", endpoints.FMOntrackViewSet)
router.register(r"datamart/fm-options", endpoints.FMOptionsViewSet)
router.register(r"datamart/funds-reservation", endpoints.FundsReservationViewSet)
router.register(r"datamart/hact/aggregate", endpoints.HACTAggreagateViewSet)
router.register(r"datamart/hact/history", endpoints.HACTHistoryViewSet)
router.register(r"datamart/interventions", endpoints.InterventionViewSet)
router.register(r"datamart/interventions-locations", endpoints.InterventionByLocationViewSet)
router.register(r"datamart/interventions-budget", endpoints.InterventionBudgetViewSet)
router.register(r"datamart/interventions-activities", endpoints.InterventionActivityViewSet)
router.register(r"datamart/interventions-country-programmes", endpoints.InterventionCPViewSet)
router.register(r"datamart/interventions-epd", endpoints.InterventionEPDViewSet)
router.register(r"datamart/interventions-management-budget", endpoints.InterventionBudgetMgmtViewSet)
router.register(r"datamart/interventions-planned-visits", endpoints.InterventionPlannedVisitsViewSet)
router.register(r"datamart/interventions-review", endpoints.InterventionReviewViewSet)

router.register(r"datamart/pd-indicators", endpoints.PDIndicatorViewSet)
router.register(r"datamart/pmp-indicators", endpoints.PMPIndicatorsViewSet)
router.register(r"datamart/user-stats", endpoints.UserStatsViewSet)

router.register(r"datamart/partners/assessment", endpoints.PartnerAssessmentViewSet)
router.register(r"datamart/partners/agreements", endpoints.PartnerAgreementViewSet)
router.register(r"datamart/partners/contacts", endpoints.PartnerStaffMemberViewSet)
router.register(r"datamart/partners/plannedengagement", endpoints.EtoolsPlannedengagementViewSet)

router.register(r"datamart/psea/assessments", endpoints.PseaAssessmentViewSet)
router.register(r"datamart/psea/answers", endpoints.PseaAnswerViewSet)

router.register(r"datamart/reports/sections", endpoints.SectionViewSet)
router.register(r"datamart/reports/indicators", endpoints.IndicatorViewSet)

router.register(r"datamart/reports/outcomes", endpoints.OutcomeViewSet, basename="outcome")
router.register(r"datamart/reports/outputs", endpoints.OutputViewSet, basename="output")
router.register(r"datamart/reports/activities", endpoints.ActivityViewSet, basename="activity")

router.register(r"datamart/users", endpoints.EtoolsUserViewSet)

router.register(r"datamart/travel/trips", endpoints.TravelTripViewSet)

router.register(r"datamart/travels", endpoints.TravelViewSet)
router.register(r"datamart/travel-activities", endpoints.TravelActivityViewSet)
router.register(r"datamart/t2f/trips", endpoints.TripViewSet)
router.register(r"datamart/tpm-visits", endpoints.TPMVisitViewSet)
router.register(r"datamart/tpm-activities", endpoints.TPMActivityViewSet)
router.register(r"datamart/partners_hact", endpoints.PartnerHactViewSet)
router.register(r"datamart/partners_hact_active", endpoints.PartnerHACTActiveViewSet)
router.register(r"datamart/partners", endpoints.PartnerViewSet, basename="partners")

router.register(r"prp/indicator-report", endpoints.IndicatorReportViewSet)
router.register(r"prp/datareport", endpoints.DataReportViewSet)

router.register(r"system/monitor", endpoints.MonitorViewSet)

from etools_datamart.apps.sources.source_prp import api_urls  # noqa isort:skip

from .endpoints.rapidpro import _urls_  # noqa isort:skip

urlpatterns = [
    re_path(r"(?P<version>(v1|v2|latest))/", include(router.urls)),
    re_path(r"\+sw(?P<format>\.json|\.yaml)$", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    path(r"+swagger/", endpoints.schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path(r"+redoc/", endpoints.schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

src/etools_datamart/config/urls.py
from django.conf import settings
from django.contrib.admin import site
from django.urls import include, path, re_path

from oauth2_provider.views import AuthorizationView

import unicef_rest_framework.urls

import etools_datamart.api.urls
from etools_datamart.apps.multitenant.views import SelectSchema

urlpatterns = [
    path(r"me/", include("etools_datamart.apps.me.urls")),
    path(r"s/", include("etools_datamart.apps.subscriptions.urls")),
    path(r"", include("etools_datamart.apps.web.urls")),
    path(r"", include("social_django.urls", namespace="social")),
    re_path(r"^authorize/?$", AuthorizationView.as_view(), name="authorize"),
    path(r"api/", include(etools_datamart.api.urls)),
    path(r"urf/", include(unicef_rest_framework.urls, namespace="urf")),
    path(r"admin/schemas/", SelectSchema.as_view(), name="select-schema"),
    path(r"admin/", site.urls),
    path(r"impersonate/", include("impersonate.urls")),
    path(r"explorer/", include("explorer.urls")),
]

if settings.DEBUG:
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
        ]
    )


def trigger_error(request):
    division_by_zero = 1 / 0  # noqa


urlpatterns += [
    path("sentry-debug/", trigger_error),
]

urlpatterns = [
    path(settings.URL_PREFIX, include(urlpatterns)),
]

src/unicef_rest_framework/urls.py
from django.contrib import admin
from django.urls import path

from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from unicef_rest_framework.views import ExportCreate, ExportFetch, ExportList, ExportUpdate

from .routers import APIRouter

admin.autodiscover()

router = APIRouter()

app_name = "urf"

urlpatterns = (
    path(r"api-token-auth/", obtain_jwt_token),
    path(r"api-token-refresh/", refresh_jwt_token),
    path(r"api-token-verify/", verify_jwt_token),
    path(r"exports/", ExportList.as_view(), name="export-list"),
    path(r"exports/<int:pk>/", ExportUpdate.as_view(), name="export-update"),
    path(r"exports/book/", ExportCreate.as_view(), name="export-create"),
    path(r"exports/fetch/<int:pk>/", ExportFetch.as_view(), name="export-fetch"),
)

src/etools_datamart/apps/mart/data/models/base.py
from django.contrib.contenttypes.models import ContentType
from django.db import models

from celery.local import class_property

# from etools_datamart.apps.mart.data import (CommonSchemaLoader, CommonSchemaLoaderOptions,
#                                             EtoolsLoader, EToolsLoaderOptions, )
from etools_datamart.apps.core.models import DataMartManager
from etools_datamart.apps.etl.base import DataMartModelBase
from etools_datamart.apps.mart.data.loader import (
    CommonSchemaLoader,
    CommonSchemaLoaderOptions,
    EtoolsLoader,
    EToolsLoaderOptions,
)


class CommonDataMartModelModelBase(DataMartModelBase):
    loader_option_class = CommonSchemaLoaderOptions
    loader_class = CommonSchemaLoader


class EToolsDataMartModelBase(CommonDataMartModelModelBase):
    loader_option_class = EToolsLoaderOptions
    loader_class = EtoolsLoader


class CommonDataMartModel(models.Model, metaclass=CommonDataMartModelModelBase):
    source_id = models.IntegerField(blank=True, null=True, db_index=True)
    last_modify_date = models.DateTimeField(blank=True, auto_now=True)
    seen = models.DateTimeField(blank=True, null=True)

    class Meta:
        abstract = True

    @class_property
    def service(self):
        from unicef_rest_framework.models import Service

        return Service.objects.get(source_model=ContentType.objects.get_for_model(self))

    @class_property
    def linked_services(self):
        from unicef_rest_framework.models import Service

        return [s for s in Service.objects.all() if s.managed_model == self]


class EtoolsDataMartModel(CommonDataMartModel, metaclass=EToolsDataMartModelBase):
    country_name = models.CharField(max_length=100)
    schema_name = models.CharField(max_length=63, db_index=True)
    area_code = models.CharField(max_length=10, db_index=True)

    class Meta:
        abstract = True
        indexes = [
            models.Index(fields=["source_id", "schema_name"]),
        ]

    objects = DataMartManager()

src/etools_datamart/apps/mart/prp/models/base.py
"""
IndicatorIndicatorlocationdata -----
1)
Country                         CoreCountry.name
Partner                         PartnerPartner.title
PD                              UnicefProgrammedocument.reference_number
Indicator Target                Reportable.target
Indicator Baseline              Reportable.baseline
Title of Indicator              Reportable.blueprint.title

d. denominatro
v. enumaror
c. calc

2)
Indicator ID                Reportable.id
Indicator Location Name         IndicatorLocationData.location.name
Indicator Location Geo          IndicatorLocationData.location.point
Admin level of location         IndicatorLocationData.location.type.admin_level
Reported Total                  IndicatorLocationData.disaggregation['()']['c']



Country                         CoreCountry.name
Partner                         PartnerPartner.title
PD                              UnicefProgrammedocument.reference_number
Indicator Target                Reportable.target
Indicator Baseline              Reportable.baseline
Title of Indicator              Reportable.blueprint.title
Calculation across periods      'sum' 'max'...
Calculation across locations    'sum' 'max'....
Means of Verification           Reportable.means_of_verification
Indicator Results level         ???
Indicator Location Name         IndicatorLocationData.location.name
Indicator Location Geo          IndicatorLocationData.location.point
Admin level of location         IndicatorLocationData.location.type.admin_level
Frequency                       IndicatorReport.frequency (Reportable, ProgrammeDocument ??)
Overall Status                  ProgressReport.review_overall_status
Narrative Assessment            IndicatorReport.narrative_assessment
Due date                        IndicatorReport.due_date
Submission date                 IndicatorReport.submission_date
Project activity                (cannot find this field maybe PartnerActivity?)

Totalbudget(ideally at most granular level tied to activity / result)
Utilised budget(same conditions as above)
Report  #
"""

from datetime import timedelta

from django.conf import settings
from django.db import transaction
from django.utils import timezone

from celery.utils.log import get_task_logger
from dateutil.utils import today
from redis.exceptions import LockError

from etools_datamart.apps.etl.exceptions import MaxRecordsException, RequiredIsMissing, RequiredIsRunning
from etools_datamart.apps.etl.loader import BaseLoader, EtlResult, load_class, logger, RUN_UNKNOWN
from etools_datamart.apps.etl.paginator import DatamartPaginator
from etools_datamart.sentry import process_exception

logger = get_task_logger(__name__)


class PrpBaseLoader(BaseLoader):
    def get_queryset(self):
        if self.config.queryset:
            ret = self.config.queryset
        elif self.config.source:
            ret = self.config.source.objects.all()
        else:  # pragma: no cover
            raise ValueError("Option must define 'queryset' or 'source' attribute")

        return ret

    def filter_queryset(self, qs):
        use_delta = self.context["only_delta"] and not self.context["is_empty"]
        if self.config.filters:
            qs = qs.filter(**self.config.filters)
        if use_delta and (self.config.last_modify_field and self.last_run):
            logger.debug(f"Loader {self}: use deltas")
            qs = qs.filter(**{f"{self.config.last_modify_field}__gte": self.last_run})
        return qs

    def load(
        self,
        *,
        verbosity=0,
        stdout=None,
        ignore_dependencies=False,
        max_records=None,
        only_delta=True,
        run_type=RUN_UNKNOWN,
        **kwargs,
    ):
        self.on_start(run_type)
        self.results = EtlResult()
        logger.debug(f"Running loader {self}")
        lock = self.lock()
        truncate = self.config.truncate
        try:
            if lock:  # pragma: no branch
                if not ignore_dependencies:
                    for requirement in self.config.depends:
                        if requirement.loader.is_running():
                            raise RequiredIsRunning(requirement)
                        requirement.loader.check_refresh()

                    for req_model_class_path in self.config.depends_as_str:
                        model_cls = load_class(req_model_class_path)
                        requirement = model_cls()
                        if requirement.loader.is_running():
                            raise RequiredIsRunning(requirement)
                        requirement.loader.check_refresh()

                self.mapping = {}
                mart_fields = self.model._meta.concrete_fields
                for field in mart_fields:
                    if field.name not in ["source_id", "id", "last_modify_date"]:
                        self.mapping[field.name] = field.name
                if self.config.mapping:  # pragma: no branch
                    self.mapping.update(self.config.mapping)
                self.update_context(
                    today=timezone.now(),
                    max_records=max_records,
                    verbosity=verbosity,
                    records=0,
                    only_delta=only_delta,
                    is_empty=not self.model.objects.exists(),
                    stdout=stdout,
                )
                sid = transaction.savepoint()
                try:
                    self.results.context = self.context
                    self.fields_to_compare = [f for f in self.mapping.keys() if f not in ["seen"]]
                    if truncate:
                        self.model.objects.truncate()
                    qs = self.filter_queryset(self.get_queryset())

                    batch_size = settings.RESULTSET_BATCH_SIZE
                    logger.debug(f"Batch size:{batch_size}")

                    paginator = DatamartPaginator(qs, batch_size)
                    for page_idx in paginator.page_range:
                        page = paginator.page(page_idx)
                        for record in page.object_list:
                            filters = self.config.key(self, record)
                            values = self.get_values(record)
                            op = self.process_record(filters, values)
                            self.increment_counter(op)

                    if stdout and verbosity > 0:
                        stdout.write("\n")

                    if self.config.sync_deleted_records(self):
                        self.remove_deleted()
                    # deleted = self.model.objects.exclude(seen=today).delete()[0]
                    # self.results.deleted = deleted
                except MaxRecordsException:
                    pass
                except BaseException:
                    transaction.savepoint_rollback(sid)
                    raise
            else:
                logger.info(f"Unable to get lock for {self}")

        except (RequiredIsMissing, RequiredIsRunning) as e:
            self.on_end(error=e, retry=True)
            raise
        except BaseException as e:
            self.on_end(e)
            process_exception(e)
            raise
        else:
            self.on_end(None)
        finally:
            if lock:  # pragma: no branch
                try:
                    lock.release()
                except LockError as e:  # pragma: no cover
                    logger.warning(e)

        return self.results

    def remove_deleted(self):
        existing = list(self.get_queryset().only("id").values_list("id", flat=True))
        to_delete = self.model.objects.exclude(source_id__in=existing)

        if self.config.archive_delta and self.config.archive_field:
            archived_excluded = {f"{self.config.archive_field}__lt": today() - timedelta(self.config.archive_delta)}
            to_delete = to_delete.exclude(**archived_excluded)

        self.results.deleted += to_delete.count()
        to_delete.delete()

src/etools_datamart/apps/web/templates/base.html
<!DOCTYPE html>{% load static datamart %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default_if_none:"eTools Datamart" }}</title>
    {% block head %}
        <link rel="icon" type="image/ico" href="{% static 'favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}?_={% version %}">
    {% endblock head %}
    {% if config.ANALYTICS_CODE %}
        <script async src="https://www.googletagmanager.com/gtag/js?id={{ config.ANALYTICS_CODE }}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }

            gtag('js', new Date());
            gtag('config', '{{ config.ANALYTICS_CODE }}');
        </script>
    {% endif %}
</head>
<body class="{{ page }}">

{% block body %}
    {% block content %}

        <div class="limiter">
            <div class="master-container">
                <div class="left">
                    {% block left %}
                        <img src="{% static 'unicef_logo2.png' %}">
                    {% endblock left %}
                </div>
                <div class="right">
                    {% block right %}
                        <form class="validate-form" method="post">
                            {% csrf_token %}
                            <div class="wrap-input100 validate-input m-b-20" data-validate="Type user name">
                                <input id="first-name" class="input100" type="text" name="username"
                                       placeholder="User name">
                                {#                            <span class="focus-input100"></span>#}
                            </div>
                            <div class="wrap-input100 validate-input m-b-20" data-validate="Type password">
                                <input class="input100" type="password" name="password" placeholder="Password">
                                {#                            <span class="focus-input100"></span>#}
                            </div>

                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn">
                                    Sign in
                                </button>
                            </div>

                        </form>
                    {% endblock right %}
                </div>
            </div>
        </div>


    {% endblock %}
{% endblock %}

{% block footer %}
    <hr/>
    <div style="float: left;padding: 10px">
        {{ user.label }}
        {% if user.is_impersonate %}
            [<a href="{% url 'impersonate-stop' %}">Back to {{ request.real_user }}</a>]
        {% endif %}

    </div>
    <div style="float: right;padding: 10px">
        Version: {% version %}
    </div>
{% endblock footer %}
{% block bottom_scripts %}
{% endblock %}

</body>
</html>

src/etools_datamart/apps/web/templates/index.html
{% extends 'base.html' %}{% load static datamart %}
{% block right %}
    <h1>eTools Datamart</h1>
    <ul class="index-menu">
        {% if request.user.is_anonymous %}
            <li><a href="{% url "api:api-root" version="latest" %}">API (needs token)</a></li>
            <li class="menu-sep h30">&nbsp;</li>
            <li class="menu-sep h30">&nbsp;</li>
            <li><a href="{% url "login" %}">Login</a></li>
        {% else %}
            <li><a href="{% url "api:api-root" version="latest" %}">API</a></li>
            <li><a href="{% url "api:schema-redoc" %}">Documentation</a></li>
            <li><a href="{% url "api:schema-swagger-ui" %}">Swagger</a></li>
            <li><a href="/status/">Service Status</a></li>
            <li><a href="{% url "monitor" %}">Monitor</a></li>
            <li><a href="{% url "profile" %}">Settings</a></li>
            <li><a href="{% url "urf:export-list" %}">Exports</a></li>
            {% if request.user.is_staff %}
                <li class="menu-sep h10">&nbsp;</li>
                <li><a href="{% url "admin:index" %}">Admin</a></li>
            {% endif %}
            {% if request.user.is_superuser %}
                <li class="menu-sep h10">&nbsp;</li>
                <li><a href="/explorer">Explorer</a></li>
                <li><a href="/flower">Flower</a></li>
                <li><a href="/rmq/">RabbitMQ</a></li>
            {% endif %}
            <li class="menu-sep h30">&nbsp;</li>
            <li class="menu-sep h30">&nbsp;</li>
            <li><a href="{% url "logout" %}">Logout</a></li>
            <li><a href="{% url "disconnect" %}">Disconnect</a></li>

        {% endif %}
    </ul>
{% endblock %}

src/etools_datamart/apps/web/templates/login.html
{% extends 'base.html' %}{% load static %}

{% block title %}Login{% endblock %}

{% block right %}
    <div class="center" id="login-menu">
        <div>
            <h2><a href='{% url "social:begin" "unicef-azuread-tenant-oauth2" %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}'>Login with Azure</a></h2>
        </div>
        <div><h4>OR</h4></div>
        <div>
            <h4><a id="local-login" href="{% url 'login' %}?local=1">Local account login</a></h4>
{#            {% if config.ALLOW_EMAIL_PASSWORD %}#}
{#                (<a href="{% url "request-access" %}">Request Access</a>)#}
{#            {% endif %}#}
        </div>
    </div>
    <div style="display: none" id="login-form">
        <form class="validate-form" method="post">
            {% csrf_token %}
            {% if form.errors %}
                <div style="padding: 5px;color:red">
                    {% for k, e in form.errors.items %}
                        {{ e }}
                    {% endfor %}
                </div>
            {% endif %}
            <span class="login100-form-title p-b-34">Account Login</span>
            <div class="wrap-input100 validate-input m-b-20" data-validate="Type user name">
                <input id="first-name" class="input100" type="text" name="username" placeholder="User name">
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 validate-input m-b-20" data-validate="Type password">
                <input class="input100" type="password" name="password" placeholder="Password">
                <span class="focus-input100"></span>
            </div>

            <div class="container-login100-form-btn">
                <button class="login100-form-btn">
                    Sign in
                </button>
            </div>
            <div>
                <div class="center" style="padding: 30px">OR</div>
                <h2 class="center"><a href="{% url "social:begin" "unicef-azuread-tenant-oauth2" %}">Login with Azure</a></h2>
            </div>
        </form>
    </div>
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script>
        var getUrlVars = function () {
            var vars = [], hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for (var i = 0; i < hashes.length; i++) {
                hash = hashes[i].split('=');
                vars.push(hash[0]);
                vars[hash[0]] = hash[1];
            }
            return vars;
        };
        var args = getUrlVars();
        if (args.local) {
            $('#login-menu').hide();
            $('#login-form').show();
        }
    </script>

{% endblock %}

src/etools_datamart/apps/web/templates/monitor.html
{% extends 'base.html' %}{% load static subscriptions %}

{% block title %}Monitor{% endblock %}

{% block content %}
    <style>
        select {
            {#background: transparent;#}
            border: none;
            font-size: 14px;
            height: 29px;
            padding: 5px; /* If you add too much padding here, the options won't show in IE */
            width: 150px;
   -webkit-border-radius: 5px;
   -moz-border-radius: 5px;
   border-radius: 5px;
        }

    </style>
    <div id="header">
        <img src="{% static 'unicef_logo.png' %}" width="100">
    </div>
    <div class="menubar">
        <span><a href="{% url "home" %}">Home</a></span>
        <span><a href="{% url "api:api-root" version="latest" %}">API</a></span>
        <span><a href="{% url "api:schema-redoc" %}">Documentation</a></span>
        {% if user.is_staff %}
            <span><a href="{% url "admin:index" %}">Admin</a></span>
        {% endif %}
    </div>
    <div id="monitor">
        <div class="row header">
            <span class="col task">Data</span>
            <span class="col last_run">Last run</span>
            <span class="col last_changes">Last change</span>
            <span class="col status">Status</span>
<!--            <span class="col subscription">Subscribe</span>-->
        </div>
        {% for t in tasks %}
            <div class="row {% cycle 'odd' 'even' %}">
                <span class="col task">{{ t.verbose_name }}</span>
                <span class="col last_run">{{ t.last_run|default_if_none:"" }}</span>
                <span class="col last_changes">{{ t.last_changes|default_if_none:"" }}</span>
                <span class="col status {{ t.status }}">{{ t.status }}</span>
<!--                <span class="col subscription">{% subscription_select t %}</span>-->
                {% if user.is_staff %}
                    <span><a href="{% url "admin:etl_etltask_change" t.pk %}">Admin</a></span>
                {% endif %}

            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block bottom_scripts %}
    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script>
        $('select').on('change', function (e) {
            console.log(e);
            console.log(e.target.id);

            $.post("{% url "subscribe" "000" %}".replace("000", e.target.id),
                JSON.stringify({"type": e.target.selectedIndex})
            ).done(function (e) {

            }).fail(function (e) {

            }).always(function (e) {

            });

        })
    </script>
{% endblock %}

src/etools_datamart/apps/web/templates/request_access.html
{% extends 'base.html' %}{% load static datamart  crispy_forms_tags %}
{% block content %}

    <div class="master-container">
        {% if done %}
            <div class="row" style="width: 90%">
                <div style="text-align: center;padding: 10px">Email sent</div>
                <div style="text-align: center;padding: 10px">Please check your UNICEF inbox</div>
                <div style="text-align: center;padding: 10px"><a href="{% url 'login' %}">Login</a></div>
            </div>
        {% elif fail %}
            <div class="row" style="width: 90%">
            </div>
        {% else %}
            <div class="box">
                <div class="right">
                    <form class="validate-form" method="post">
                        {% csrf_token %}
                        {{ form.email.errors }}
                        <div class="wrap-input100 validate-input m-b-20" data-validate="Type UNICEF email">
                            {{ form.email }}
                        </div>
                        <div class="container-login100-form-btn">
                            <button class="login100-form-btn">
                                Send request
                            </button>
                        </div>

                    </form>
                </div>
                <div class="left">
                    <div>
                        <ul>
                            <li>Please indicate your UNICEF email.</li>
                            <li>If eligible you will receive your password shortly.</li>
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}